name: Neprekinjena integracija

on: # Kdaj se začne izvajanje delovnega toka?
  push:
    branches:
      - testno-okolje # Ob vsaki uveljavitvi na veji testno-okolje.
    paths-ignore:
      - "README.md" # Ignoriramo spremembe v dokumentaciji.

jobs:
  build:
    runs-on: # Okolje, v katerem se testi izvedejo.
      - ubuntu-latest
    strategy:
      matrix:
        node-verzija:
          - 15.x
    steps: # Posamezni koraki testiranja.
      - uses: actions/checkout@v2 # Pridobimo izvorno kodo repozitorija.
      - name: Uporabi Node.js $15.11.0 # Nastavi Node.js okolje.
        uses: actions/setup-node@v1
        with:
          node-version: $15.11.0
      - run: npm install # Namesti knjižnice.
      - run: npx cypress run # Poženi teste.
